package com.multicert.test.resource;

import com.multicert.test.service.dto.EsClientDTO;
import com.multicert.test.service.dto.PtClientDTO;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.Map;

@Path("v1")
@Api(value = "Generic Api for general functions", consumes = MediaType.APPLICATION_JSON, produces = MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface ClientResource {


    @GET
    @Path("{country}/client")
    @ApiOperation(value = "Get a List of Clients Paginated")
    Response getClientList(@PathParam("country") String country, @QueryParam("page") Integer page, @QueryParam("size") Integer size);

    @DELETE
    @Path("{country}/client/{id}")
    @ApiOperation(value = "Delete a client must use the id generated by the system")
    Response deleteClient(@PathParam("country") String country, @PathParam("id") Long id);

    @GET
    @Path("{country}/client/fiscalnumber/{fiscalnumber}")
    @ApiOperation(value = "Retrieve a client by the nin")
    Response getClientByNif(@PathParam("country") String country, @PathParam("fiscalnumber") String nif);

    @GET
    @Path("{country}/client/name/{name}")
    @ApiOperation(value = "Retrieve a list of clients that contains a name | the name doesn't need to be cases sensitive or complete")
    Response getClientByName(@PathParam("country") String country, @PathParam("name") String name);

    @POST
    @Path("{country}/client")
    @ApiOperation(value = "Create Client with the values provided")
    Response createClient(@PathParam("country") String country, Map<String, Object> client);

    @POST
    @Path("config/{country}")
    @ApiOperation(value = "Create Client with the values provided")
    Response configCountry(@PathParam("country") String country, Map<String, Object> body);
}
