package com.multicert.test.resource;

import com.multicert.test.service.dto.ClientDTO;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("")
@Api(value = "Hello resource Version 1", consumes = MediaType.APPLICATION_JSON, produces = MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface ClientResource {

    @POST
    @Path("v1/client")
    @ApiOperation(value = "Create Client with the values provided")
    Response createClient(ClientDTO clientDTO);

    @GET
    @Path("v1/client")
    @ApiOperation(value = "Get a List of Clients Paginated")
    Response getClientList(@QueryParam("page") Integer page, @QueryParam("size") Integer size);

    @DELETE
    @Path("v1/client/{id}")
    @ApiOperation(value = "Delete a client must use the id generated by the system")
    Response deleteClient(@PathParam("id") Long id);

    @GET
    @Path("v1/client/nif/{nif}")
    @ApiOperation(value = "Retrieve a client by the nin")
    Response getClientByNif(@PathParam("nif") String nif);

    @GET
    @Path("v1/client/name/{name}")
    @ApiOperation(value = "Retrieve a list of clients that contains a name | the name doesn't need to be cases sensitive or complete")
    Response getClientByName(@PathParam("name") String name);
}
